config/routes.rb
Rails.application.routes.draw do
  
  root 'rooms#index'
  # resources :home, only: [:index, :show]
  namespace :home do
    get :setting
  end
  resources :rooms
  resources :friends, only: [:index, :new] do
    patch :follow
    patch :unfollow
    patch :block
    patch :unblock
  end
  namespace :friends do
    patch :search
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'users'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_user, only: [:follow, :unfollow, :block, :unblock]
  
  def index
    if params[:options] == 'blocked'
      @blocked_users = current_user.blocked_users
    elsif params[:options] == 'recommend'
      @followed_users = current_user.recommend_users
    else
      @group_rooms = current_user.rooms.groups
      @friend_users = current_user.following
    end
  end
  
  def new
  end
  
  def search
    @user = User.find_by(email: params[:email])
    
    if @user
      flash.now[:notice] = "#{params[:email]}が見つかりました！"
    else
      flash.now[:alert] = "#{params[:email]}は見つかりません。"
    end
    
    render 'new'
  end
  
  def follow
    if current_user.following?(@user)
      flash.now[:alert] = "#{@user.name}はすでに友達になっています。"
      render 'new'
    elsif current_user.blocked?(@user)
      flash.now[:notice] = "#{@user.name}のブロックを解除しました。"
      redirect_to friends_url
    else
      current_user.follow(@user)
      flash.now[:notice] = "#{@user.name}を友達に追加しました。"
      redirect_to friends_url
    end
  end
  
  def unfollow
    current_user.unfollow(@user)
    
    redirect_to friends_url, alert: "#{@user.name}の友達を解除しました。"
  end
  
  def block
    current_user.block(@user)
    
    redirect_to friends_url, alert: "#{@user.name}をブロックしました。"
  end
  
  def unblock
    current_user.unblock(@user)
    
    redirect_to friends_url, alert: "#{@user.name}をブロックしました。"
  end
  
  private
  
  def set_user
    @user = User.find(params[:friend_id])
  end
end

app/views/friends/index.html.erb
<% if @blocked_users %>
  <h2>友達</h2>
  <% @blocked_users.each do |user| %>
    <p><%= link_to user.name, users_path(user) %>　<%= link_to "ブロック解除", friend_unblock_path(user), method: :patch %></p>
  <% end %>

<% elsif @followed_users %>
  <h2>友達</h2>
  <% @followed_users.each do |user| %>
    <p><%= link_to user.name, users_path(user) %>　<%= link_to "友達に追加", friend_follow_path(user), method: :patch %></p>
  <% end %>

<% else %>
  <h2>グループ</h2>
  <% @group_rooms.each do |room| %>
    <%= link_to room.title, room_path(room) %>
  <% end %>

  <h2>友達</h2>
  <% @friend_users.each do |user| %>
    <p><%= link_to user.name, users_path(user) %>　<%= link_to "ブロック", friend_block_path(user), method: :patch %></p>
  <% end %>

  <%= link_to "+（友達を探す）", new_friend_path %>
<% end %>

app/views/friends/new.html.erb
<h2>友達を探す</h2>

<%= form_tag friends_search_path, method: :patch do %>
  <%= label_tag "email" %>
  <%= email_field_tag "email", @user ? @user.email : "" %>
  <%= submit_tag "探す" %>
<% end %>
<br />

<% if @user %>
  <h4>名前: <%= @user.name %></h4>
  <P>Email: <%= @user.email %></P>
  
  <% if current_user.following?(@user) %>
    <p>すでに友達に追加されています。</p>
  <% elsif current_user.blocked?(@user) %>
    <%= link_to "ブロックを解除する", friend_unblock_path(@user), method: :patch %>
  <% else %>
    <%= link_to "友達に追加する", friend_follow_path(@user), method: :patch %>
  <% end %>
<% end %>