config/routes.rb
Rails.application.routes.draw do
  
  root 'rooms#index'
  # resources :home, only: [:index, :show]
  namespace :home do
    get :setting
  end
  resources :rooms
  resources :friends, only: [:index, :new] do
    patch :follow
    patch :unfollow
    patch :block
    patch :unblock
  end
  namespace :friends do
    patch :search
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'users'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def setting
    
  end
  
  # def index
  # end
  # 
  # def show
  # end
end

app/views/home/index.html.erb
<h3><%= link_to "グループを作成する", new_room_path %></h3>

app/views/home/setting.html.erb
<h2>グループ設定</h2>
<ul>
  <li><%= link_to "グループを作成", new_room_path %></li>
</ul>

<h2>ユーザー設定</h2>
<ul>
  <li><%= link_to "ユーザー情報詳細", users_path(current_user) %></li>
  <li><%= link_to 'ユーザ情報設定', edit_user_registration_path %></li>
  <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
</ul>

<h2>友達設定</h2>
<ul>
  <li><%= link_to "友達を探す", new_friend_path %></li>
  <li><%= link_to "友達かも？", friends_path(options: 'recommend') %></li>
  <li><%= link_to "ブロックリスト", friends_path(options: 'blocked') %></li>
</ul>

app/views/home/show.html.erb
<h1>Home#show</h1>
<p>Find me in app/views/home/show.html.erb</p>