config/routes.rb
Rails.application.routes.draw do
  
  root 'rooms#index'
  # resources :home, only: [:index, :show]
  namespace :home do
    get :setting
  end
  resources :rooms
  resources :friends, only: [:index, :new] do
    patch :follow
    patch :unfollow
    patch :block
    patch :unblock
  end
  namespace :friends do
    patch :search
  end
  
  devise_for :users, controllers: { registrations: 'users/registrations' }
  devise_scope :user do
    get 'users/:id', to: 'users/registrations#show', as: 'users'
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id                        :integer          not null, primary key
#  name                      :string
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#  deleted_at                :integer
#  participants              :integer          default("0"), not null
#  is_group                  :boolean          default("f"), not null
#  latest_message_created_at :integer
#

class Room < ApplicationRecord
  acts_as_paranoid
  
  before_create :set_latest_message_created_at
  before_save :set_participants
  
  has_many :messages
  has_many :user_rooms
  has_many :users, through: :user_rooms
  
  validates :name, length: { maximum: 100 }
  validates :participants, presence: true
  
  scope :groups, -> {
    where('participants > 2')
  }
  
  scope :one_on_one, -> {
    where(participants: 2)
  }
  
  scope :newest, -> {
    order("latest_message_created_at DESC")
  }
  
  def title
    users = self.users
    user_count = users.count
    
    case user_count
    when 1
      title = users[0].name
    when 2
      title = users[1].name
    else
      title = self.name.present? ? self.name : "グループ"
    end
    self.is_group? ? title + "（#{user_count}）" : title
  end
  
  def channel
    "room_channel_#{self.id}"
  end
  
  def can_add?(user)
    is_exist = !!self.users.find_by(email: user.email)
    
    is_group ? !is_exist : (!is_exist && self.users.count < 2)
  end
  
  def add_user(user)
    self.users << user if can_add?(user)
  end
  
  private
  
  def set_latest_message_created_at
    self.latest_message_created_at = self.created_at
  end
  
  def set_participants
    self.participants = self.users.count
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_room, only: [:edit, :update, :destroy, :show]
  before_action :set_friend_users, only: [:new, :edit]
  
  def new
    @room = Room.new
  end
  
  def create
    @room = current_user.rooms.create(room_params)
    add_users if params[:user_ids].present?
    
    if flash.now[:alert]
      render 'edit'
    else
      redirect_to room_url(@room), notice: flash.now[:notice]
    end
  end
  
  def edit
  end
  
  def update
    @room.update(room_params)
    add_users if params[:user_ids].present?
    
    if flash.now[:alert]
      render 'edit'
    else
      redirect_to root_url, notice: flash.now[:notice]
    end
  end
  
  def destroy
    @room.destroy
    
    redirect_to root_url, notice: flash.now[:notice]
  end
  
  def index
    @rooms = current_user.rooms.newest
  end
  
  def show
  end
  
  private
  
  def room_params
    params.permit(
      :name,
      :is_group,
    )
  end
  
  def set_room
    @room = current_user.rooms.find(params[:id])
  end
  
  def set_friend_users
    @friend_users = current_user.following
  end
  
  def add_users
    # nil・空文字・重複を消す
    # user_emails = params[:user_emails].values.reject(&:blank?).uniq
    add_cuccess, add_fail = [], []
    return_users = []
    
    params[:user_ids].each do |user_id|
      user = User.find(user_id.to_i)
      if user && @room.can_add?(user)
        @room.add_user(user)
        return_users << user
        add_cuccess << user.name
      else
        add_fail << user.name
      end
    end
    
    flash.now[:notice] = "友達を追加しました。#{add_cuccess.join(' ')}" unless add_cuccess.empty?
    flash.now[:alert] = "友達を追加できませんでした。#{add_fail.join(' ')}" unless add_fail.empty?
    
    if add_fail.empty?
      return_users
    else
      nil
    end
  end
end

app/views/rooms/edit.html.erb
<h2>グループを編集する</h2>

<%= form_tag(room_path(@room), method: "patch") do %>
  <div class="name">
    <%= label_tag :name, "グループ名" %>
    <%= text_field_tag "name", @room.name %>
  </div>
  <br />
  <div class="users">
    <h4>招待するユーザー</h4>
    <ul>
    <% @friend_users.each_with_index do |user, i| %>
      <% if @room.can_add?(user) %>
      <li><%= check_box_tag "user_ids[]", user.id %>
      <%= label_tag "user_ids[#{user.id}]", user.name %></li>
      <% end %>
    <% end %>
  </div>
  
  <br />
  <%= hidden_field_tag "is_group", true %>
  
  <%= submit_tag "保存" %>
<% end %>

app/views/rooms/index.html.erb
<h2>チャットルーム一覧</h2>

<% if @rooms.present? %>
  <% @rooms.each do |room| %>
    <p><%= room.latest_message_created_at.strftime("%d日 (%H:%M)") %>　<%= link_to room.title, room_path(room) %>　　<%= link_to "編集", edit_room_path(room) %>　<%= link_to "削除", room_path(room), method: :delete, data: { confirm: "本当にチャットルーム#{room.name}を削除しますか？" } %></p>
  <% end %>
<% end %>

app/views/rooms/new.html.erb
<h2>グループを作成する</h2>

<%= form_tag(rooms_path, method: "post") do %>
  <div class="name">
    <%= label_tag :name, "グループ名" %>
    <%= text_field_tag "name" %>
  </div>
  <br />
  <div class="users">
    <h4>招待するユーザー</h4>
    <ul>
    <% @friend_users.each_with_index do |user, i| %>
      <li><%= check_box_tag "user_ids[]", user.id %>
      <%= label_tag "user_ids[#{user.id}]", user.name %></li>
    <% end %>
  </div>
  
  <br />
  <%= hidden_field_tag "is_group", true %>
  
  <%= submit_tag "グループ作成" %>
<% end %>

app/views/rooms/show.html.erb
<h1><%= @room.title %></h1>

<div id="messages">
  <%= render @room.messages.order_for_chat_room %>
</div>

<form>
  <input type="text" class="js-content">
  <input type="hidden" class="js-user-id" value="<%= current_user.id %>">
  <button class="js-submit-button">投稿</button>
</form>

<%# room_idを元にチャンネル作成をするために、関数化して引数（room_id）を渡す %>
<%= javascript_tag do %>
  $(document).ready(function(){
    App.MakeRoomChannel(<%= @room.id %>)
  });
<% end %>